---
- name: Openscap Report 
  hosts: all
  strategy: free
  become: true
  vars:
    oscap_profile: xccdf_py.com.miempresa_profile_custom-hardening-lab
    data_stream_home: "/usr/share/xml/scap/ssg/content/"
  tasks:
    - name: Run scan CentOS
      shell: "oscap xccdf eval --profile {{ oscap_profile }} 
      --report /tmp/{{ inventory_hostname }}.html 
      --tailoring-file {{ data_stream_home }}ssg-{{ ansible_distribution }}{{ ansible_distribution_major_version }}-ds-tailoring-custom-lab.xml
                       {{ data_stream_home }}ssg-centos{{ ansible_distribution_major_version }}-ds.xml"
      register: result
      when: ansible_distribution == "CentOS"
      ignore_errors: yes
      failed_when: result.rc >= 3

    - name: Run scan RedHat
      shell: "oscap xccdf eval --profile {{ oscap_profile }} 
      --report /tmp/{{ inventory_hostname }}.html 
      --tailoring-file {{ data_stream_home }}ssg-{{ ansible_distribution }}{{ ansible_distribution_major_version }}-ds-tailoring-custom-lab.xml
                       {{ data_stream_home }}ssg-rhel{{ ansible_distribution_major_version }}-ds.xml"
      when: ansible_distribution == "RedHat"
      ignore_errors: yes
      failed_when: result.rc >= 3

    - name: Copy the report to the ansible master
      fetch:
        src: /tmp/{{ inventory_hostname }}.html
        dest: files/hardening_reports/ 
        flat: yes

    - name: Clean up
      file:
        path: /tmp/{{ inventory_hostname }}.html
        state: absent
...
